# Generated by Django 4.2.6 on 2023-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categorymodel_alter_productmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formmodel',
            options={'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(to='products.categorymodel'),
        ),
    ]
