# Generated by Django 4.2.6 on 2023-10-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_formmodel_options_productmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='comment',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
