# Generated by Django 4.2.6 on 2023-10-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_formmodel_age_alter_formmodel_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='city',
            field=models.IntegerField(default=0, verbose_name='Город'),
        ),
    ]
