# Generated by Django 4.2.6 on 2023-10-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_formmodel_age_formmodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Город'),
        ),
    ]
